name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Check out repo code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        python -m venv venv
        source venv/bin/activate
        python -m pip install -r requirements.txt

    - name: Build coverage file
      run: |
        python -m pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=. tests | tee pytest-coverage.txt

    - name: Run tests
      run: |
        python -m pytest -v tests

    - name: Pytest coverage comment
      uses: aazizk/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml